#if !defined GPIO_CFG_H_GUARD
#define GPIO_CFG_H_GUARD

typedef enum {
    GPIO_PIN_LED,
    GPIO_PIN_RELAY1,
    GPIO_PIN_RELAY2,
    GPIO_PIN_RELAY3,
    GPIO_PIN_RELAY4,
    GPIO_PIN_BUTTON1,
    GPIO_PIN_BUTTON2,
    GPIO_PIN_BUTTON3,
    GPIO_PIN_BUTTON4,
    GPIO_PIN_BUTTON5,
    GPIO_PIN_BUTTON6,
    GPIO_PIN_BUTTON7,
    GPIO_PIN_BUTTON8,
    GPIO_PIN_SENTINEL,
} Gpio_Pin;

#endif

